name: nst-app
channels:
  - anaconda
  - conda-forge
  - pytorch
dependencies:
  - python=3.7.9
  - pip=20.2.4
  - numpy=1.19.1
  - pytorch=1.8.1
  - torchvision=0.9.1
  - pip:
    - opencv-python
    - streamlit